%YAML:1.0
---

#路口的设备总数 4是十字路口，3是T型路口
mec_num: 4

#当前数据的设备序号，即哪一台设备所采集的数据

data_num: 2

calib_path: "../../83_2/"
rtk_file: "GPS_ins.txt"
radar_path: "radar/"    #radar文件夹,以 “/” 结尾


#83号路口
#以1号radar坐标为全局原点：
lat0: 39.08245244
lon0: 117.0434205
height0: -7.038

#1号雷达GPS坐标:
lat1: 39.08245244
lon1: 117.0434205
height1: -7.038

#2号雷达GPS坐标:
lat2: 39.08179735
lon2: 117.04361432
height2: -7.104

#3号雷达GPS坐标:
lat3: 39.08169408
lon3: 117.04278509
height3: -7.072

#4号雷达GPS坐标:
lat4: 39.08232708
lon4: 117.04261154
height4: -7.100

#84号路口
#以1号radar坐标为全局原点：
# lat0: 39.07633051
# lon0: 117.0462822
# height0: -6.644

# #1号雷达GPS坐标:
# lat1: 39.07633051
# lon1: 117.0462822
# height1: -6.644

# #2号雷达GPS坐标:
# lat2: 39.07576076
# lon2: 117.0464923
# height2: -6.325

# #3号雷达GPS坐标:
# lat3: 39.07547653
# lon3: 117.0456503
# height3: -6.158

# #4号雷达GPS坐标:
# lat4: 39.07604811
# lon4: 117.0453622
# height4: -6.368
